import NavBar from '@/components/app-layout/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Insomnia Lab Test',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' style={{ display: 'inherit' }}>
			<body className={inter.className}>
				<NavBar />
				<main className='pb-20 pt-28'>{children}</main>
			</body>
		</html>
	);
}
